### ISSUE TITLE
make t1 boomerang turret shoot less boomerang and make boomerang turret shoot far before returning

### ISSUE THREAD

**Issue by lokyinng** [Sh1penfire/Endless-rusting#4]
yes t1 boomerang turret shoot too much boomerang that create lag

**Comment by Sh1penfire** [comment]
what did you expect?
This isn't in the actual release yet, as the firing speed and range of boomerangs as well as the ammo needed has and will be changed

About the shooting far thing, I'd rather not, as the turrets already are powerful enough against groups as is.
