### ISSUE TITLE
Try to open Volen chanels - crash.

### ISSUE THREAD

**Issue by Creater3d** [Sh1penfire/Endless-Rusting#4]
[crash-report-02_13_2022_21_57_10.txt](https://github.com/Sh1penfire/Endless-Rusting/files/8056536/crash-report-02_13_2022_21_57_10.txt)

**Comment by Sh1penfire** [comment]
sorry for the (very) late response, did you have any prior saves in Volen before, did you just launch to Volen or something else?
I am unsure to help here. The only things I can inference from this currently is one of the blocks could possibly have failed to save, or some weird crap happened with mindustry.io.SaveFileReader.readChunk

**Comment by Creater3d** [comment]
How possible connect with you discord or telegram?

**Comment by Creater3d** [comment]
[crash-report-03_05_2022_12_12_50.txt](https://github.com/Sh1penfire/Endless-Rusting/files/8190458/crash-report-03_05_2022_12_12_50.txt)

![3](https://user-images.githubusercontent.com/73776761/156879389-651a125f-e780-4142-8e6f-b6042faee389.png)

![4](https://user-images.githubusercontent.com/73776761/156879394-02e06022-30ec-4cfb-9437-a40dff9ccaf6.png)

![5](https://user-images.githubusercontent.com/73776761/156879398-e4755ffe-892d-4073-8d17-071e369d9237.png)

**Comment by Creater3d** [comment]
Possible make second orbit without second sun?

**Comment by Creater3d** [comment]
[crash-report-03_05_2022_14_09_00.txt](https://github.com/Sh1penfire/Endless-Rusting/files/8190629/crash-report-03_05_2022_14_09_00.txt)
