### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by Creater3d** [Sh1penfire/Endless-Rusting#6]
Mindustry 126.2 crash at start on Sulpur Sea.
[crash-report-03_28_2022_17_51_51.txt](https://github.com/Sh1penfire/Endless-Rusting/files/8364010/crash-report-03_28_2022_17_51_51.txt)

**Comment by Sh1penfire** [comment]
steps to recreate the bug?

**Comment by Creater3d** [comment]
? - it is my direction to fix?
