### ISSUE TITLE
Fix map Volen channels.

### ISSUE THREAD

**Issue by Creater3d** [Sh1penfire/Endless-Rusting#7]
Turn off sandbox mode when playing in camping.

**Comment by Creater3d** [comment]
Why close?

**Comment by Sh1penfire** [comment]
this issue was already fixed, I am unable to go onto your device and remove the map file however so volen still has infinite resources
to fix this, locate the map file in your storage and delete it

**Comment by Creater3d** [comment]
I try.

сб, 7 мая 2022 г. в 15:35, Sh1penfire ***@***.***>:

**Comment by Creater3d** [comment]
This version just for 126.2 or can use for 135?

сб, 7 мая 2022 г. в 16:21, 1 3 ***@***.***>:

**Comment by Creater3d** [comment]
In map folder - not have Volen channel.
[image: image.png]

сб, 7 мая 2022 г. в 15:35, Sh1penfire ***@***.***>:
