### ISSUE TITLE
Need fix.

### ISSUE THREAD

**Issue by Creater3d** [Sh1penfire/Endless-Rusting#9]
Mode not have some blocks for Sulphur seas map - need compilling from "Endles rusting demo", wehen possible make?

**Comment by Sh1penfire** [comment]
Im sorry, whats the issue here?

**Comment by Creater3d** [comment]
Good day, Sulfur Seas can only be played and edited when the demo mod is
enabled. If it's just the Endless Rusting mod, then the map knocks out. since
there are no blocks that are in the demo version. When you turn on the
normal and demo mod - 2 planets are created and it would be nice if there
was only one sun that comes with a serpulo. When the normal mode is on,
another sun appears. And why does not confirm the request to friends. I'm
on discord - Creater3d#3915.

вт, 10 мая 2022 г. в 05:12, Sh1penfire ***@***.***>:

**Comment by Sh1penfire** [comment]
Most maps including Sulphur Seas are being heavily changed or reworked in the coming update. I am not going to spend time on maps that will be removed. Thank you for submitting this issue for others to see.
